# Generated by Django 3.2.13 on 2022-07-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.PositiveIntegerField(choices=[(1, 'Open'), (2, 'Close')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.PositiveIntegerField(choices=[(1, 'Tarif 1'), (2, 'Tarif 2'), (3, 'Tarif 3')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Phisical'), (2, 'Legal')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Commercial'), (2, 'Non commercial')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=100)),
                ('first_last_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('img', models.ImageField(upload_to='')),
                ('rating', models.IntegerField()),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.status')),
                ('stack', models.ManyToManyField(to='main_app.Stack')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('members_limit', models.IntegerField()),
                ('deadline', models.DateField()),
                ('rating', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.users')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.direction')),
                ('id_project_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.typeproject')),
                ('id_rate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.rate')),
                ('id_stage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.stage')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.public')),
            ],
        ),
    ]
