# Generated by Django 3.2.13 on 2022-10-06 06:30

from django.conf import settings
import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'нужно сделать'), (2, 'в процессе'), (3, 'готово'), (4, 'архив')], default=1)),
                ('description', models.CharField(default='Описание задачи', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='direction',
        ),
        migrations.AddField(
            model_name='project',
            name='colour',
            field=models.CharField(default='green', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Описание проекта', verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.TextField(verbose_name='Направление проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок окончания проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id_project_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.typeproject', verbose_name='Тип проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.rate', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.public', verbose_name='Доступность проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Список участников'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members_limit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальное количество участников'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Рейтинг'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='main_app_pr_name_6d2053_gin'),
        ),
        migrations.AddField(
            model_name='task',
            name='profile',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.project'),
        ),
    ]
