# Generated by Django 3.2.13 on 2022-09-22 04:51

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='main_app_pr_name_6d2053_gin'),
        ),
    ]
