# Generated by Django 3.2.13 on 2022-11-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='command',
            field=models.CharField(blank=True, max_length=100, verbose_name='Наличие команды'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
