# Generated by Django 3.2.13 on 2022-09-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project_main_app_pr_name_6d2053_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='colour',
            field=models.CharField(default='green', max_length=20),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.TextField(verbose_name='Направление проекта'),
        ),
    ]
