# Generated by Django 3.2.13 on 2022-10-19 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20221006_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ManyToManyField(blank=True, related_name='profile_project', to=settings.AUTH_USER_MODEL, verbose_name='Список участников'),
        ),
    ]
