# Generated by Django 3.2.13 on 2022-09-29 07:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220929_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, verbose_name='Срок окончания проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id_project_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.typeproject', verbose_name='Тип проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.rate', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.public', verbose_name='Доступность проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Список участников'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members_limit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальное количество участников'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Рейтинг'),
        ),
    ]
