# Generated by Django 3.2.13 on 2022-10-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_project_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='direction',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Описание проекта', verbose_name='Описание проекта'),
        ),
    ]
