# Generated by Django 3.2.13 on 2022-10-30 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20221029_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='tag',
            field=models.ManyToManyField(to='main_app.Stack'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('US', 'Пользователь'), ('MO', 'Администратор')], default='US', max_length=2),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.idea')),
            ],
        ),
    ]
