# Generated by Django 3.2.13 on 2022-10-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20221030_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='tag',
            new_name='stack',
        ),
    ]
