# Generated by Django 3.2.13 on 2022-11-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20221101_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.CharField(blank=True, max_length=256, verbose_name='Достижения'),
        ),
    ]
