# Generated by Django 3.2.13 on 2022-11-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='command',
            field=models.CharField(blank=True, max_length=3, verbose_name='Наличие команды'),
        ),
        migrations.AddField(
            model_name='profile',
            name='direction',
            field=models.CharField(blank=True, max_length=256, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(blank=True, to='main_app.Stack', verbose_name='Навыки'),
        ),
    ]
