# Generated by Django 3.2.13 on 2022-11-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20221101_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthday',
            new_name='dateofbirth',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='skill',
            new_name='stack',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='direction',
        ),
        migrations.AddField(
            model_name='profile',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='citizenship',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.ManyToManyField(blank=True, to='main_app.Profession', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_in_command',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
