# Generated by Django 3.2.13 on 2022-11-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=128, verbose_name='Направление'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stack',
        ),
        migrations.AddField(
            model_name='profile',
            name='stack',
            field=models.CharField(blank=True, max_length=128, verbose_name='Навыки'),
        ),
    ]
